### ISSUE TITLE
Start a User(models.Model) object

### ISSUE THREAD

**Issue by alexrosenfeld10** [batcole/T10#4]
Lesser priority, but will be needed after more of the wireframing and overall structure is up.

**Comment by tdorobantu** [comment]
please see tudor-dorobantu-patch-2 and  tudor-dorobantu-patch-3 branch

**Comment by tdorobantu** [comment]
created new branch for main/models.py. Modifications brought to models.py in new branch include Many-to-Many relationship between Profile(user) and Movie.
